import { getAntinodeLocationCount } from "../2024-08";
import { readFileSync } from "graceful-fs";

const testInput = `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`;

const fullInput = readFileSync("2024/08/2024-08.txt", "utf8");

describe("AOC-2024-08", () => {
  it("part1-test returns count of unique antinodes", () => {
    expect(getAntinodeLocationCount(testInput)).toBe(14);
  });

  it("part1-full returns count of unique antinodes", () => {
    expect(getAntinodeLocationCount(fullInput)).toBe(240);
  });
});
